name: postal_code_jp
author: Kazuki Yamaguchi <y.kazuki0614n@gmail.com>
version: 1.2.0
homepage: https://github.com/yamarkz/postal_code_jp
description: A dart package for Japan Post official postal code, a.k.a zip code, search and update.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  csv: ^5.0.0
  yaml: ^3.1.0
  intl: ^0.17.0
  archive: ^3.1.2
dev_dependencies: 
  test: ^1.17.4
